# Gerado automaticamente para o Kitty
background #141129
foreground #cfdae2
selection_background #373449
selection_foreground #cfdae2

color0  #141129
color1  #2D2A4B
color2  #3E415E
color3  #2FCAE7
color4  #532E3B
color5  #80919B
color6  #532E3B
color7  #cfdae2

color8  #666473
color9  #6c6981
color10 #777a8e
color11 #2FCAE7
color12 #866c75
color13 #80919B
color14 #866c75
color15 #ffffff
