# Gerado automaticamente para o Kitty
background #333A53
foreground #cfdae2
selection_background #51576c
selection_foreground #cfdae2

color0  #333A53
color1  #477388
color2  #ACAEBC
color3  #6291A3
color4  #B59B78
color5  #DAD9E3
color6  #B59B78
color7  #cfdae2

color8  #7a7e8f
color9  #7e9dab
color10 #c4c6d0
color11 #6291A3
color12 #cbb9a0
color13 #DAD9E3
color14 #cbb9a0
color15 #ffffff
