# Gerado automaticamente para hyprlock
$bg       = rgb(141129)
$surface  = rgb(373449)
$fg       = rgb(cfdae2)
$muted    = rgb(666473)

$accent   = rgb(80919B)
$red      = rgb(2D2A4B)
$yellow   = rgb(2FCAE7)
$green    = rgb(3E415E)
$blue     = rgb(532E3B)

# cores de texto/UI
$time_hour   = rgb(80919B)
$time_minute = rgb(532E3B)
$date_color  = rgb(cfdae2)
$user_color  = rgb(cfdae2)
$outer_color = rgb(80919B)
$inner_color = rgb(373449)
$font_color  = rgb(cfdae2)
$song_color  = rgb(80919B)
