# Gerado automaticamente para hyprlock
$bg       = rgb(333A53)
$surface  = rgb(51576c)
$fg       = rgb(cfdae2)
$muted    = rgb(7a7e8f)

$accent   = rgb(DAD9E3)
$red      = rgb(477388)
$yellow   = rgb(6291A3)
$green    = rgb(ACAEBC)
$blue     = rgb(B59B78)

# cores de texto/UI
$time_hour   = rgb(DAD9E3)
$time_minute = rgb(B59B78)
$date_color  = rgb(cfdae2)
$user_color  = rgb(cfdae2)
$outer_color = rgb(DAD9E3)
$inner_color = rgb(51576c)
$font_color  = rgb(cfdae2)
$song_color  = rgb(DAD9E3)
