# Gerado automaticamente para hyprlock
$bg       = rgb(16142C)
$surface  = rgb(38374b)
$fg       = rgb(cfdae2)
$muted    = rgb(676675)

$accent   = rgb(849CAD)
$red      = rgb(2C264A)
$yellow   = rgb(324264)
$green    = rgb(4C3553)
$blue     = rgb(5B4B6A)

# cores de texto/UI
$time_hour   = rgb(849CAD)
$time_minute = rgb(5B4B6A)
$date_color  = rgb(cfdae2)
$user_color  = rgb(cfdae2)
$outer_color = rgb(849CAD)
$inner_color = rgb(38374b)
$font_color  = rgb(cfdae2)
$song_color  = rgb(849CAD)
