# sexo = variaveis #

source = variavéis.conf
source = keybinds.conf
source = animações.conf
source = decoracao.conf


################
### MONITORS ###
################


monitor=auto,1366x768@60,0x0,1



#################
### AUTOSTART ###
#################


exec-once = waybar
exec-once = mpvpaper -o "--loop-file=inf --no-audio" '*' /home/sam/.Wallpapers/miku.mp4

#############################
### ENVIRONMENT VARIABLES ##
#############################


env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#############
### INPUT ###
#############


input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 

    touchpad {
        natural_scroll = false
    }
}


gesture = 3, horizontal, workspace


device {
    name = epic-mouse-v1
    sensitivity = -0.5
}




##############################
### WINDOWS AND WORKSPACES ###
##############################



